name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza diariamente à meia-noite
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Update README
        run: |
          python update_readme.py
          
      - name: Commit and push if README.md updated
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with latest stats" || exit 0
          git push
              - nome: gerar-jogo-snake-from-github-contribution-grid
                usos: Platane/snk@v3.2.0
            
